import React from 'react'
import '../../../styles/bodyP5.css'

export default function BodyP5() {
    return (
        <div className='bP5'>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, provident. Velit, fugit. Fugit, similique. Officia reiciendis, ipsum ab illum repellat cupiditate tempore impedit repellendus nostrum veniam dolorum debitis dolorem quis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab omnis cum laborum dolor adipisci quidem totam, magnam voluptatem doloribus eveniet quis, temporibus minima facilis quisquam! Quia dolorum esse deserunt fuga.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quisquam ipsum totam neque suscipit voluptatibus nulla corrupti laudantium. Similique obcaecati nostrum, dolorum iure deserunt odit molestiae eaque sequi corrupti error.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit dolores magni voluptas porro eaque dolor minima, quos obcaecati, modi et voluptatibus magnam dolorem tempora quae, laudantium nam odit est voluptatum!</p>
        </div>
    )
}